function x = parameterization_Optimize(fun, optObj, optimizer)

    switch optimizer
        case "LS"
            % non-linear least squares optimization. 
            options = optimoptions('lsqnonlin',...
                                         'Display', 'iter-detailed',...
                                         'PlotFcns', 'optimplotx', ...
                                         'FunctionTolerance', 1e-20, ...
                                         'OptimalityTolerance', 1e-20, ...
                                         'MaxFunctionEvaluations', 1e10, ...
                                         'MaxIterations', 20, ...
                                         'StepTolerance', 1e-16, ...
                                         'Algorithm', 'trust-region-reflective',...
                                         'UseParallel',true);

            x = lsqnonlin(fun, optObj.param, optObj.lb, optObj.ub, options);
        case "PSO"
            % particle-swarm optimization. 

            options = optimoptions('particleswarm',...
                                         'Display', 'iter',...
                                         'UseParallel', true,...
                                         'InitialSwarmMatrix', optObj.param', ...
                                         'PlotFcns', 'pswplotbestf', ...
                                         'SwarmSize', 5000, ...
                                         'MaxIterations', 20,...%50, ...
                                         'FunctionTolerance', 0.01, ...
                                         'ObjectiveLimit', 0.01, ...
                                         'MaxStallIterations', 100);%1000);

            x = particleswarm(fun, length(optObj.param), optObj.lb, optObj.ub, options);
        case "GA"
            % Genetic algorithm optimization
            
            options = optimoptions('ga',...
                                   'PopInitRange', [lb; ub],...
                                   'PopulationSize', 5000,... 
                                   'Generations', 10,...
                                   'InitialPopulation', optObj.param,...
                                   'FunctionTolerance', 0.01, ...
                                   'MaxStallGenerations', 100,...
                                   'Display', 'diagnose',...
                                   'PlotFcns', {@gaplotbestf @gaplotbestindiv},...
                                   'UseVectorized', false,...
                                   'UseParallel', true);
           nvars = length(optObj.param); 
           x = ga(fun, nvars, [], [], [], [], optObj.lb, optObj.ub, [], [], options);
    end
end

